name: Update Open Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install runner (tsx)
        run: npm i -g tsx

      # Assumes the user has committed get-openreadme.ts at the repo root
      - name: Refresh Open Readme image
        run: tsx get-openreadme.ts
