name: Generate Profile Images

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'user-mapping.json'
      - '.github/workflows/generate-profiles.yml'

permissions:
  contents: write  # Required for pushing changes
  pull-requests: write  # Required for creating pull requests

jobs:
  generate-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Read user mappings
        id: user-mappings
        run: |
          # Read the user-mapping.json file
          MAPPINGS=$(jq -r 'to_entries | map("\(.key)=\(.value)") | join(" ")' data/user-mapping.json)
          echo "mappings=${MAPPINGS}" >> $GITHUB_OUTPUT

      - name: Generate profile images
        env:
          IMAGE_TOKEN: ${{ secrets.IMAGE_TOKEN }}
        run: |
          # Install required dependencies
          npm install node-fetch@2

          # Create the generation script
          cat > generate-images.js << 'EOL'
          const fs = require('fs');
          const fetch = require('node-fetch');
          const { execSync } = require('child_process');

          // Get the API URL from environment variables
          const API_URL = process.env.API_URL || 'http://localhost:3000';
          const IMAGE_TOKEN = process.env.IMAGE_TOKEN;

          async function generateProfileImage(username, userId) {
            try {
              console.log(`Generating image for ${username}...`);

              // First, get the user data from GitHub API
              const userResponse = await fetch(`https://api.github.com/users/${username}`, {
                headers: {
                  'Authorization': `token ${IMAGE_TOKEN}`,
                  'Accept': 'application/vnd.github.v3+json'
                }
              });

              if (!userResponse.ok) {
                throw new Error(`GitHub API error: ${userResponse.statusText}`);
              }

              const userData = await userResponse.json();

              // Prepare the data for the OpenReadme API
              // Build the API URL with all parameters
              const params = new URLSearchParams({
                n: userData.name || username,
                i: userData.avatar_url || '',
                g: username,
                x: userData.twitter_username || '',
                l: '',  // LinkedIn would need to be handled separately
                p: userData.blog || userData.html_url,
                t: 'classic'  // Default theme
              });

              const apiUrl = `${API_URL}?${params.toString()}`;
              console.log(`Calling API: ${apiUrl}`);

              // Call the OpenReadme API with proper headers
              const response = await fetch(apiUrl, {
                method: 'GET',
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json'
                }
              });

              console.log(`Response status: ${response.status} ${response.statusText}`);

              if (!response.ok) {
                const error = await response.text();
                throw new Error(`API error: ${error}`);
              }

              const result = await response.json();
              console.log(`✅ Successfully generated image for ${username}: ${result.url}`);

              return result.url;

            } catch (error) {
              console.error(`❌ Error generating image for ${username}:`, error.message);
              return null;
            }
          }

          // Process all users
          (async () => {
            const mappings = process.env.MAPPINGS.split(' ');
            console.log(`Found ${mappings.length} users to process`);

            for (const mapping of mappings) {
              if (!mapping) continue;

              const [username, userId] = mapping.split('=');
              if (!username || !userId) continue;

              console.log(`\n--- Processing ${username} (${userId}) ---`);

              try {
                const imageUrl = await generateProfileImage(username, userId);
                if (imageUrl) {
                  // Here you could update the user-mapping.json with the new image URL if needed
                  console.log(`Image URL: ${imageUrl}`);
                }

                // Add delay to avoid rate limiting (1 second between requests)
                await new Promise(resolve => setTimeout(resolve, 1000));

              } catch (error) {
                console.error(`Error processing ${username}:`, error);
              }
            }

            console.log('\n--- All users processed ---');
          })();
          EOL

          # Run the generation script
          MAPPINGS="${{ steps.user-mappings.outputs.mappings }}" \
          API_URL="https://openreadme.vercel.app/api/openreadme" \
          IMAGE_TOKEN="${{ secrets.IMAGE_TOKEN }}" \
          node generate-images.js

      - name: Commit and push changes
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        env:
          IMAGE_TOKEN: ${{ secrets.IMAGE_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git config --global --add safe.directory /github/workspace
          git add .
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "chore: update profile images [skip ci]" && \
             git push https://${{ github.actor }}:$IMAGE_TOKEN@github.com/${{ github.repository }}.git HEAD:main)
